version: "3.9"
services:
  db:
    image: postgres:14
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: ./payment-app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./payment-app:/payment-app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgres://postgres:password@db"
    depends_on:
      - db

volumes:
  postgres-data: