---
name: Run tests in feature branch
on:
  push:
    branches:
      - '*'
      - '!main'
jobs:
  rspec:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./payment-app
    env:
      RAILS_ENV: test
  
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: "password"
          POSTGRES_DB: postgres
          # needed because the postgres container does not provide a healthcheck
          # tmpfs makes DB faster by using RAM
          options: >-
            --mount type=tmpfs,destination=/var/lib/postgresql/data
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
        ports:
          - 5432:5432
    
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.22.5

      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Ruby and check for gem cache
        uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
        with:
          ruby-version: 3.0.1
          bundler-cache: true
          working-directory: ./payment-app

      - name: Bundle gems
        run: bundle install

      - name: Install node packages for Webpacker
        run: yarn install --pure-lockfile

      - name: Pre-compile assets for testing
        run: bundle exec rails assets:precompile

      - name: Set up the application database
        run: "bundle exec rails db:setup && bundle exec rails db:migrate"
        env:
          DATABASE_URL: "postgres://postgres:password@localhost"

      - name: Run rspec tests
        run: bundle exec rspec spec
        env:
          DATABASE_URL: "postgres://postgres:password@localhost"

